name: Update Bing Wallpaper
on:
  schedule:
    - cron: '00 16 * * *'
  workflow_dispatch:
jobs:
  update-bing-wallpaper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout(检出代码)
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 7
          # 使用 pnpm 安装依赖
          run_install: true

      - name: 设置 node 运行环境
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 pnpm 依赖
          cache: pnpm

      - name: loadLastImage(获取 bing 最新图片信息)
        run: pnpm BingWallpaper:loadLastImage

      - name: commit(提交变更到 git 本地仓库)
        run: |
          git config --local user.email "answer-3@qq.com"
          git config --local user.name "answer-3"
          git pull
          git add -A
          git commit -m "update by github actions"

      - name: push(推送到 github 远程仓库)
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: main