name: Update Bing Wallpaper
on:
  schedule:
    - cron: '00 16 * * *'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  update-bing-wallpaper:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout(检出代码)
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 7
          # 使用 pnpm 安装依赖
          run_install: true

      - name: 设置 node 运行环境
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 pnpm 依赖
          cache: pnpm

      - name: loadLastImage(获取 bing 最新图片信息)
        run: pnpm BingWallpaper:loadLastImage

      - name: commit(提交变更到 git 本地仓库)
        run: |
          git config --local user.email "answer-3@qq.com"
          git config --local user.name "answer-3"
          git pull
          git add -A
          git commit -m "update by github actions"
          git push

      - name: updateMD
        run: pnpm BingWallpaper:updateMD

      - name: build
        run: pnpm BingWallpaper:build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './src/BingWallpaper/.vuepress/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1